### PR TITLE
Moved all entities to mapped-superclasses for better extensibility

### PR DESCRIPTION
**Pull request by kortwotze**
Can you also please tag a version of this for Sylius 1.3?

### CODE REVIEW

**Comment by bartoszpietrzak1994** [comment]
Thank you, Peter! :tada:

**Comment by kortwotze** [comment]
Can we please have this tagged for sylius 1.3? Or is 1.3. completely not supported anymore?

**Comment by Zales0123** [comment]
I believe it can be a little bit hard :/ We do not support Sylius 1.3 [since February](https://github.com/Sylius/RbacPlugin/pull/48) and we already use some features from Sylius 1.4 (like a billing data on a Channel entity) 😢

**Comment by kortwotze** [comment]
Allright. I am just asking :)

**Pull request merged**
